name: Windows Testing

on:
  push:
  # schedule:
  #   - cron: "50 1 * * *"
    branches:
      - main
  workflow_dispatch:
    branches:

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        pip install -r requirements.txt
    - name: Install SeleniumBase
      run: |
        pip install .
    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Get chrome-headless-shell
      run: |
        sbase get chs
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
    # - name: Make sure nosetests is working
    #   run: |
    #     echo "def test_2(): pass" > nothing2.py
    #     nosetests nothing2.py
    # - name: Run pytest examples/unit_tests/verify_framework.py --browser=chrome --headless
    #   run: |
    #     pytest examples/unit_tests/verify_framework.py --browser=chrome --headless -v -s --junit-xml=junit/test-results.xml
    # - name: Run pytest examples/offline_examples --browser=chrome --headless --rs
    #   run: |
    #     pytest examples/offline_examples --rs --browser=chrome --headless -v -s --junit-xml=junit/test-results.xml
    # - name: Run pytest examples/boilerplate_test.py --browser=chrome --headless
    #   run: |
    #     pytest examples/boilerplates/boilerplate_test.py --browser=chrome --headless -v -s --junit-xml=junit/test-results.xml
    # - name: Run pytest examples/test_window_switching.py --browser=chrome --headless
    #   run: |
    #     pytest examples/test_window_switching.py --browser=chrome --headless -v -s --junit-xml=junit/test-results.xml
    # - name: Verify seleniumbase install from PyPI
    #   run: |
    #     pip install seleniumbase -U --no-deps --force-reinstall --no-cache-dir
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v3
    - name: Custom Script to Test cloudflare
      run: |
        python examples/raw_recaptcha.py --browser=chrome
