name: Windows Testing # Name remains as per user's request, but runs on Linux now

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest # Changed from macos-latest to ubuntu-latest for Xvfb and apt-get compatibility
    env:
      PY_COLORS: "1"
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies for Chrome and Xvfb
      # Google Chrome is needed for SeleniumBase
      # xvfb is needed for virtual display if not running in strict headless mode
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        # Ensure 'requests' is installed for the proxy script
        pip install -r requirements.txt requests

    - name: Install SeleniumBase
      run: |
        pip install . # Assuming . refers to the root of your SeleniumBase project

    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase

    - name: Install chromedriver (SeleniumBase handles this usually)
      # This step might be redundant if SeleniumBase auto-manages drivers,
      # but keeping it as it was in your original file.
      run: |
        seleniumbase install chromedriver

    - name: Get chrome-headless-shell
      run: |
        sbase get chs

    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py

    # --- Proxy Integration Starts Here ---
    - name: Get and Set Proxy Environment Variable
      # This step runs your Python script to fetch a proxy
      # and sets the SELENIUM_PROXY environment variable for subsequent steps.
      run: python examples/get_proxy.py # Adjust path if your script is in a subfolder
    # --- Proxy Integration Ends Here ---

    # Original Xvfb setup (now redundant if using xvfb=True in SeleniumBase directly)
    # Keeping it as is from your original, but generally, SeleniumBase's xvfb=True
    # handles this internally without needing a separate Xvfb_launcher.sh for Python scripts.
    - run: |
        # xvfb installed above with apt-get
        python -m pip install pyautogui # If your script uses pyautogui
        # chmod +x integrations/linux/Xvfb_launcher.sh # This script is Linux-specific
        # integrations/linux/Xvfb_launcher.sh # This script would launch Xvfb manually

    - name: Custom Script to Test cloudflare with Proxy
      # Now, the SELENIUM_PROXY environment variable is available.
      # We pass its value to the SeleniumBase script using the --proxy argument.
      run: |
        python examples/raw_recaptcha.py --browser=chrome --proxy="${{ env.SELENIUM_PROXY }}"
      env:
        # Explicitly pass SELENIUM_PROXY as an environment variable to the step
        # This makes it available directly within the command's environment.
        SELENIUM_PROXY: ${{ env.SELENIUM_PROXY }}

    - name: Upload Logs (Optional, for debugging)
      if: always() # Uploads even if previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: selenium-logs
        path: latest_logs/ # This is where SeleniumBase saves its logs and screenshots
